import React, { createContext, useState, useContext, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type LocaleType = 'en' | 'hi' | 'cg';

interface LanguageContextProps {
  locale: LocaleType;
  setLocale: (locale: LocaleType) => void;
  t: (key: string) => string;
}

const translations: Record<LocaleType, Record<string, string>> = {
  en: {
    // Tabs & General
    dashboard: "Dashboard",
    children: "Children",
    notifications: "Notifications",
    profile: "Profile",
    reports: "Reports",
    funds: "Funds",
    
    // Dashboard
    parentPortal: "Parent Portal",
    welcomeBack: "Welcome back, Caregiver!",
    vitalsSummary: "Vitals Summary",
    weight: "Weight",
    height: "Height",
    muac: "MUAC",
    growthTrend: "Growth Trend",
    recoveryTimeline: "Recovery Timeline",
    screeningJourney: "Screening Journey",
    assignedFacility: "Assigned Facility",
    mitaninSupport: "Mitanin Support",
    recentAlerts: "Recent Alerts",
    registerChildBtn: "Register Child",
    callBtn: "Call Center",
    messageMitanin: "Message worker...",
    weightGain: "weight gain",
    weightLoss: "weight loss",
    noChange: "no change",
    screeningTip: "Growth Screening Reminder",
    screeningIntervalSam: "Screening every 15 days is recommended for children diagnosed with SAM/MAM to monitor recovery closely.",
    screeningIntervalNormal: "Screening every 30 days is recommended for healthy children to track standard development.",
    recoveryMilestones: "Recovery Journey Milestones",
    facilityHelp: "Pediatric Referral Facility",
    noAlerts: "No recent notifications received.",

    // Children Screen
    childrenList: "Children Registry",
    searchPlaceholder: "Search child or village...",
    all: "All",
    sam: "SAM",
    mam: "MAM",
    healthy: "Healthy",
    viewProfile: "View Profile",
    noChildren: "No children found.",
    districtLabel: "District",
    villageLabel: "Village",
    dobLabel: "DOB",
    retryBtn: "Retry Load",
    errorLoading: "Failed to load registered child profiles.",

    // Child Details
    childDetails: "Child Details",
    clinicalAdvice: "Clinical Recommendations",
    growthChart: "Growth Development Chart",
    weightHistory: "Weight Over Time (kg)",
    assessmentLog: "Clinical Assessment Logs",
    date: "Date",
    dob: "DOB",
    gender: "Gender",
    nrcCenter: "NRC Center",
    notAssigned: "Not Assigned",
    noLogs: "No vital assessment logs recorded yet.",
    admissionBtn: "Admit to NRC Facility",
    admittedNrc: "Admitted at NRC",

    // Profile
    myProfile: "My Profile",
    accountSettings: "Account Settings",
    editProfile: "Edit Profile Details",
    regDistrict: "Registered District",
    securityPassword: "Security & Password",
    preferencesHelp: "Preferences & Help",
    notifSettings: "Notification Settings",
    langSelector: "Language Selector",
    supportHelpline: "Support & Helpline",
    termsPrivacy: "Terms & Privacy Policy",
    logout: "Logout",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    nameLabel: "Caregiver Name",
    phoneLabel: "Registered Phone Number",
    selectDistrict: "Select District",
    biometrics: "Biometric Login (Face ID/Fingerprint)",
    criticalAlertsOpt: "Critical Malnutrition Alerts",
    followupRemindersOpt: "Follow-up Appointment Reminders",
    helplineUpdatesOpt: "Helpline Emergency Updates",
    applyLanguageBtn: "Apply Selected Language",
    supportIntro: "Direct dialing support directories to reach pediatric staff and health supervisors:",
    stateWcd: "State WCD Helpline",
    stateWcdDesc: "Queries regarding Anganwadis & nutrition kits",
    emergencyHealth: "Emergency Health Response",
    emergencyHealthDesc: "Pediatric diagnostics & general health advice",
    mitaninSupportLine: "Mitanin Support Helpline",
    mitaninSupportLineDesc: "Queries regarding field worker visits & local screenings",
    childInfo: "Child Information",
    childName: "Child Full Name",
    measurements: "Measurements",
    parentMobile: "Parent Mobile",
    healthStatus: "Health Status",
    locationDetails: "Location Details",
    village: "Village / Ward Area",
    anganwadiCode: "Anganwadi Center Code",
    registerBtn: "Register Child",
    childRegistrationTitle: "Child Registration",
    samIntakeForm: "SAM intake form",
    childFullName: "Child Full Name",
    enterChildName: "Enter child full name",
    dobPlaceholder: "DD/MM/YYYY",
    male: "Male",
    female: "Female",
    others: "Others",
    selectGenderError: "Select gender",
    motherName: "Mother's Name",
    enterMotherName: "Enter mother or guardian name",
    parentMobilePlaceholder: "10-digit phone number",
    weightKg: "Weight (kg)",
    heightCm: "Height (cm)",
    muacMm: "MUAC (mm)",
    villageWard: "Village / Ward Area",
    enterVillage: "Enter village or ward area",
    enterAnganwadiCode: "Enter Anganwadi code",
    submitRegistration: "Submit Registration",
    cancelRegistration: "Cancel registration",
    saving: "Saving...",
    nameRequired: "Child full name is required",
    dobRequired: "Date of birth is required",
    dobFormat: "Use DD/MM/YYYY format",
    motherNameRequired: "Mother's name is required",
    mobileFormat: "Mobile number must be 10 digits",
    weightRequired: "Weight is required",
    heightRequired: "Height is required",
    muacRequired: "MUAC is required",
    districtRequired: "District is required",
    anganwadiRequired: "Anganwadi code is required",
    villageRequired: "Village / area is required",
    regComplete: "Registration Complete",
    regCompleteDesc: "Child record has been added.",
    regFailed: "Registration Failed",
    regFailedDesc: "Unable to save child record.",
    ok: "OK",
    enterName: "Enter your name",
    securityAccess: "Security & Access",
    secureOtpActive: "Secure SMS OTP Login Active",
    secureOtpDesc: "This portal uses secure one-time-passcode (OTP) verifications to lock details and eliminate password phishing. Codes are sent to +91 ",
    biometricsDesc: "Authenticate using device FaceID or TouchID",
    activeSession: "Current Active Session",
    activeDeviceAccess: "Active Device Access (Primary Mobile)",
    closeSecurity: "Close Security Panel",
    notifPreferences: "Notification Preferences",
    criticalAlertsDesc: "SMS alerts for diagnostic transfers or immediate referrals",
    followupRemindersDesc: "SMS alerts sent 48 hours prior to Anganwadi screenings",
    helplineUpdatesDesc: "Announcements regarding health camps and pediatric services",
    saveNotifSettings: "Save Notifications Settings",
    preferencesSaved: "Preferences Saved",
    notifPreferencesUpdated: "Your system notification preferences were updated.",
    termsScopeTitle: "1. Scope of the Application",
    termsScopeText: "This portal is developed to assist child screening (SAM/MAM cases) in Chhattisgarh, working under guidelines from the National Health Mission and Integrated Child Development Services (ICDS).",
    termsPrivacyTitle: "2. Health Data Privacy",
    termsPrivacyText: "Pediatric metrics, weight records, and height screening dates are protected under e-governance security standards. No information is sold or distributed for commercial services.",
    termsSecurityTitle: "3. Security Measures",
    termsSecurityText: "Mobile number verifications and secure token storage ensure that health registries remain authentic and free from unauthorized tampering.",
    acceptUnderstand: "I Accept & Understand",
    logoutBtnText: "Logout from Registry",
    confirmLogout: "Confirm Logout",
    logoutMessage: "Are you sure you want to log out of the NRC e-Governance portal?",
    successLabel: "Success",
    profileUpdated: "Profile updated successfully",
    errorLabel: "Error",
    nameRequiredCaregiver: "Name is required",
    failedUpdate: "Failed to update profile",
    appVersionText: "App Version 1.0.0 (NIC Chhattisgarh) · Developed under WCD Department",
    verifiedAccount: "Verified Account",

    // Districts
    raipur: "Raipur",
    durg: "Durg",
    bastar: "Bastar",
    bilaspur: "Bilaspur",
    rajnandgaon: "Rajnandgaon",

    // Input Placeholders
    weightPlaceholder: "e.g. 8.5",
    heightPlaceholder: "e.g. 72",
    muacPlaceholder: "e.g. 112",

    // Landing Page
    landingTitle: "NRC e-Governance",
    landingSubtitle: "A unified platform for nutrition rehabilitation monitoring across Chhattisgarh.",
    officialPortal: "Official Portal",
    registerTitle: "Register",
    registerSub: "Secure onboarding for field staff and caregivers.",
    registerMobileBtn: "Register with Mobile",
    registerGmailBtn: "Register with Gmail",
    loginTitle: "Login",
    loginSub: "Access your dashboard, reports, and child records instantly.",
    loginPasswordBtn: "Login with Password",
    loginOtpBtn: "Login with OTP",
    nrcCentersStat: "NRC Centers",
    childrenMonitoredStat: "Children Monitored",
    samRecoveryStat: "SAM Recovery",
    trustedGov: "Trusted by Government Agencies",
    platformTrustText: "The platform is built for transparency, empowerment, and real-time decision-making in the NRC ecosystem.",
    poweredByNic: "Powered by NIC · Ministry of Women & Child Development",

    // Login Screen
    govCg: "Government of Chhattisgarh",
    nrcGovPortal: "NRC e-Governance Portal",
    welcome: "Welcome!",
    loginPhoneSub: "Login with your phone number",
    enterOtpSub: "Enter OTP sent to your phone",
    mobileNumber: "Mobile Number",
    enterMobilePlaceholder: "Enter your 10-digit mobile number",
    requestOtp: "Request OTP",
    enterOtp: "Enter OTP",
    enterOtpPlaceholder: "Enter 6-digit OTP",
    verifyOtp: "Verify OTP",
    backPhoneEntry: "Back to Phone Entry",
    secureGovPortalText: "This is a secure government portal. Unauthorized access is prohibited.",
    dontHaveAccount: "Don't have an account?",
    createAccount: "Create Account",
    phoneRequired: "Please enter a valid phone number",
    otpRequired: "Please enter a valid OTP",
    otpSentSuccess: "OTP sent successfully",
    failedSendOtp: "Failed to send OTP",
    invalidOtp: "Invalid OTP",

    // Register Screen
    startRegistration: "Start your registration",
    welcomeNrcGov: "Welcome to NRC e-Governance",
    registerCardCopy: "Choose your preferred way to create a secure account and access government services.",
    professionalRole: "Professional Role",
    selectRole: "Select role",
    govEmailLabel: "Government Email (required for non-Parent roles)",
    govEmailPlaceholder: "name@domain.gov.in",
    selectRoleError: "Please select a professional role",
    govEmailRequired: "Government email is required for non-parent roles",
    gmailRegisterAlertTitle: "Google OAuth",
    gmailRegisterAlertMsg: "Google registration integration will use Expo AuthSession.",

    // OTP Verification
    verifyMobileNum: "Verify Mobile Number",
    mobileNumLogin: "Mobile Number Login",
    enterOtpReg: "Enter OTP to continue registration",
    receiveCodeMobile: "Receive a one-time code on your mobile",
    sendOtpBtn: "Send OTP",
    verificationCode: "Verification Code",
    verifyContinueBtn: "Verify & Continue",
    verifyLoginBtn: "Verify & Login",
    useDiffNum: "Use different number",
    secureVerification: "Secure verification",
    otpValidityNote: "OTP is valid only for a short time and is used to protect your account with a trusted government login experience.",
    otpSentTitle: "OTP Sent",
    otpSentMsg: "Your verification code has been sent.",
    enterOtpCodeError: "Enter the 6-digit OTP",
    otpVerificationFailed: "OTP verification failed",

    // Full Registration
    fullRegistrationTitle: "Full Registration",
    completeDetailsText: "Complete your account details to finish registration.",
    fullNameLabel: "Full Name",
    enterFullName: "Enter your full name",
    emailAddressLabel: "Email Address",
    enterEmailAddress: "name@example.com",
    createPasswordPlaceholder: "Create password",
    confirmPasswordPlaceholder: "Confirm password",
    fieldsRequiredError: "All fields are required.",
    passwordsMismatchError: "Passwords do not match.",
    regSuccessTitle: "Registration complete",
    regSuccessMsg: "Your account has been successfully created.",
    continueBtn: "Continue",
    infoProtectedTitle: "Your information is protected",
    infoProtectedBody: "All registration details are stored securely and used only for authorized NRC e-Governance access.",

    // Component label keys
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    govPortalManagedText: "This portal is managed by the Government of Chhattisgarh and built for trusted public service access.",
    mothersName: "Mother's Name",
    mothersPhone: "Mother's Phone",
    anganwadiVillage: "Anganwadi Village",
    lastAssessmentDate: "Last Assessment Date",
    referToNrc: "Refer to Nutrition Rehab Centre",
    admittedToNrcTitle: "ADMITTED TO NUTRITION FACILITY",
    familyContextTitle: "Family Context & Information",
    samDiagnosticsIdentified: "SAM Diagnostics Identified",
    growthProgressRegistered: "Growth Progress Registered",
    mamDiagnosticCheck: "MAM Diagnostic Check",
    standardHealthRecalibrated: "Standard Health Recalibrated",
    totalRegisteredProfiles: "Total Registered Profiles",
    syncingRegistry: "Syncing state registry...",
    syncFailed: "Synchronization Failed",
    matchingRecords: "matching records",
    registryEmpty: "Registry Empty",
    noChildrenSync: "No children profile details have been synchronized. Click below to retry.",
    allNotificationsMarkedRead: "All notifications marked as read",
    clearNotifications: "Clear Notifications",
    confirmDeleteAllNotifications: "Are you sure you want to delete all notification records?",
    clearAll: "Clear All",
    unreadNotifications: "Unread Notifications",
    followupsTab: "Followups",
    alertsTab: "Alerts",
    nrcReferralsTab: "NRC Referrals",
    markAllRead: "Mark all read",
    clearAllAction: "Clear all",
    registeredStep: "Registered",
    screenedStep: "Screened",
    referredStep: "Referred",
    nrcAdmittedStep: "NRC Admitted",
    noChildrenRegistered: "No Children Registered",
    selectChildProfile: "Select Child Profile",
    viewDevelopmentHistory: "View Development History & Charts",
    remindersNutritionalTips: "Reminders & Nutritional Tips",
    nextAssessmentDue: "Next Assessment Due",
    scheduledFor: "Scheduled for approx.",
    checksRequiredBimonthly: "Checks are required bi-monthly.",
    nutritionalGuideline: "Nutritional Guideline",
    dashboardFooterText: "Department of Women & Child Development · Government of Chhattisgarh",
    activeBedCapacityAvailable: "Active bed capacity available in {district} district. Tap to confirm admission.",
    recSamFormula: "Initiate F-75 therapeutic formula (75 kcal/100ml) immediately under medical supervision.",
    recMamFormula: "Distribute 2 packets of supplementary ready-to-use therapeutic food (RUTF) daily.",
    recHealthyFormula: "Height-for-age is normal. Maintain active immunization, micronutrient powders, and bi-monthly checkups.",
    recMuacWarning: "Measure MUAC every 7 days. If MUAC decreases below 110mm, refer for immediate emergency care.",
    assignedDistrictHospitalNrc: "Assigned District Hospital NRC Center",
    activeReferralPlacement: "ACTIVE REFERRAL & PLACEMENT",
    callCenterCoordinator: "Call Center Coordinator",
    primaryCareFacility: "PRIMARY CARE FACILITY",
    anganwadiCenterAwc: "Anganwadi Center (AWC)",
    localVillageCenter: "Local Village Center",
    icdsProgram: "Program: Integrated Child Development Services (ICDS)",
    messageMitaninField: "Message Mitanin / Field Worker",
    registerChildDesc: "Register your child using your mobile number to view diagnostic growth, track follow-up schedules, and receive nutritional recommendations.",
    adviceSamGuide: "Provide therapeutic RUTF and F-75 milk formulas; avoid hard solid grains until next clinical assessment.",
    adviceNormalGuide: "Ensure daily supplementary nutrition from local Anganwadi center, emphasizing proteins and iron.",
  },
  hi: {
    // Tabs & General
    dashboard: "डैशबोर्ड",
    children: "बच्चे",
    notifications: "सूचनाएं",
    profile: "प्रोफाइल",
    reports: "रिपोर्ट",
    funds: "फंड",
    
    // Dashboard
    parentPortal: "अभिभावक पोर्टल",
    welcomeBack: "आपका स्वागत है, अभिभावक!",
    vitalsSummary: "स्वास्थ्य संकेतक",
    weight: "वजन",
    height: "ऊंचाई",
    muac: "एमयूएसी (MUAC)",
    growthTrend: "विकास की प्रवृत्ति",
    recoveryTimeline: "रिकवरी समयरेखा",
    screeningJourney: "स्क्रीनिंग यात्रा",
    assignedFacility: "आवंटित स्वास्थ्य केंद्र",
    mitaninSupport: "मितानिन सहायता",
    recentAlerts: "हालिया अलर्ट",
    registerChildBtn: "बच्चे का पंजीकरण करें",
    callBtn: "कॉल करें",
    messageMitanin: "मितानिन को संदेश भेजें...",
    weightGain: "वजन में वृद्धि",
    weightLoss: "वजन में कमी",
    noChange: "कोई बदलाव नहीं",
    screeningTip: "विकास स्क्रीनिंग अनुस्मारक",
    screeningIntervalSam: "सैम/मैम (SAM/MAM) से पीड़ित बच्चों की बारीकी से रिकवरी की निगरानी के लिए हर 15 दिनों में स्क्रीनिंग की सलाह दी जाती है।",
    screeningIntervalNormal: "स्वस्थ बच्चों के सामान्य विकास को ट्रैक करने के लिए हर 30 दिनों में स्क्रीनिंग की सलाह दी जाती है।",
    recoveryMilestones: "रिकवरी यात्रा के मील के पत्थर",
    facilityHelp: "बाल चिकित्सा रेफरल सुविधा",
    noAlerts: "कोई नया नोटिफिकेशन नहीं मिला है।",

    // Children Screen
    childrenList: "बच्चों की सूची",
    searchPlaceholder: "बच्चे या गाँव का नाम खोजें...",
    all: "सभी",
    sam: "सैम (SAM)",
    mam: "मैम (MAM)",
    healthy: "स्वस्थ",
    viewProfile: "प्रोफाइल देखें",
    noChildren: "कोई बच्चा नहीं मिला।",
    districtLabel: "जिला",
    villageLabel: "गाँव",
    dobLabel: "जन्म तिथि",
    retryBtn: "पुनः प्रयास करें",
    errorLoading: "पंजीकृत बच्चों की प्रोफाइल लोड करने में विफल।",

    // Child Details
    childDetails: "बच्चे का विवरण",
    clinicalAdvice: "चिकित्सीय सलाह",
    growthChart: "विकास चार्ट",
    weightHistory: "समय के साथ वजन (किग्रा)",
    assessmentLog: "मूल्यांकन लॉग विवरण",
    date: "तारीख",
    dob: "जन्म तिथि",
    gender: "लिंग",
    nrcCenter: "एनआरसी (NRC) केंद्र",
    notAssigned: "आवंटित नहीं",
    noLogs: "अभी तक कोई स्वास्थ्य रिकॉर्ड दर्ज नहीं किया गया है।",
    admissionBtn: "एनआरसी में भर्ती करें",
    admittedNrc: "एनआरसी में भर्ती है",

    // Profile
    myProfile: "मेरी प्रोफाइल",
    accountSettings: "खाता सेटिंग्स",
    editProfile: "प्रोफाइल विवरण संपादित करें",
    regDistrict: "पंजीकृत जिला",
    securityPassword: "सुरक्षा और पासवर्ड",
    preferencesHelp: "प्राथमिकताएं और सहायता",
    notifSettings: "अधिसूचना सेटिंग्स",
    langSelector: "भाषा चयनकर्ता",
    supportHelpline: "सहायता और हेल्पलाइन",
    termsPrivacy: "नियम और गोपनीयता नीति",
    logout: "लॉगआउट",
    saveChanges: "सहेजें",
    cancel: "रद्द करें",
    nameLabel: "अभिभावक का नाम",
    phoneLabel: "पंजीकृत मोबाइल नंबर",
    selectDistrict: "जिला चुनें",
    biometrics: "बायोमेट्रिक लॉगिन (Face ID/फिंगरप्रिंट)",
    criticalAlertsOpt: "गंभीर कुपोषण अलर्ट प्राप्त करें",
    followupRemindersOpt: "फॉलो-अप अपॉइंटमेंट अनुस्मारक",
    helplineUpdatesOpt: "हेल्पलाइन आपातकालीन अपडेट",
    applyLanguageBtn: "चुनी गई भाषा लागू करें",
    supportIntro: "बाल चिकित्सा कर्मचारियों और स्वास्थ्य पर्यवेक्षकों तक पहुंचने के लिए सीधे डायल करें:",
    stateWcd: "राज्य महिला एवं बाल विकास हेल्पलाइन",
    stateWcdDesc: "आंगनवाड़ियों और पोषण किट के संबंध में प्रश्न",
    emergencyHealth: "आपातकालीन स्वास्थ्य सहायता",
    emergencyHealthDesc: "बच्चों के स्वास्थ्य और उपचार के लिए सलाह",
    mitaninSupportLine: "मितानिन सहायता हेल्पलाइन",
    mitaninSupportLineDesc: "फील्ड वर्कर दौरों और स्थानीय स्क्रीनिंग के संबंध में प्रश्न",
    childInfo: "बच्चे की जानकारी",
    childName: "बच्चे का पूरा नाम",
    measurements: "शारीरिक माप",
    parentMobile: "अभिभावक का मोबाइल नंबर",
    healthStatus: "स्वास्थ्य स्थिति",
    locationDetails: "स्थान विवरण",
    village: "गाँव / वार्ड क्षेत्र",
    anganwadiCode: "आंगनवाड़ी केंद्र कोड",
    registerBtn: "पंजीकरण करें",
    childRegistrationTitle: "बाल पंजीकरण",
    samIntakeForm: "सैम (SAM) प्रवेश फॉर्म",
    childFullName: "बच्चे का पूरा नाम",
    enterChildName: "बच्चे का पूरा नाम दर्ज करें",
    dobPlaceholder: "दिन/महीना/साल",
    male: "पुरुष",
    female: "महिला",
    others: "अन्य",
    selectGenderError: "लिंग चुनें",
    motherName: "माता का नाम",
    enterMotherName: "माता या अभिभावक का नाम दर्ज करें",
    parentMobilePlaceholder: "10-अंकीय मोबाइल नंबर",
    weightKg: "वजन (किग्रा)",
    heightCm: "ऊंचाई (सेमी)",
    muacMm: "एमयूएसी (मिमी)",
    villageWard: "गाँव / वार्ड क्षेत्र",
    enterVillage: "गाँव या वार्ड क्षेत्र दर्ज करें",
    enterAnganwadiCode: "आंगनवाड़ी कोड दर्ज करें",
    submitRegistration: "पंजीकरण जमा करें",
    cancelRegistration: "पंजीकरण रद्द करें",
    saving: "सहेज रहा है...",
    nameRequired: "बच्चे का पूरा नाम आवश्यक है",
    dobRequired: "जन्म तिथि आवश्यक है",
    dobFormat: "DD/MM/YYYY प्रारूप का उपयोग करें",
    motherNameRequired: "माता का नाम आवश्यक है",
    mobileFormat: "मोबाइल नंबर 10 अंकों का होना चाहिए",
    weightRequired: "वजन आवश्यक है",
    heightRequired: "ऊंचाई आवश्यक है",
    muacRequired: "एमयूएसी आवश्यक है",
    districtRequired: "जिला आवश्यक है",
    anganwadiRequired: "आंगनवाड़ी कोड आवश्यक है",
    villageRequired: "गाँव / क्षेत्र आवश्यक है",
    regComplete: "पंजीकरण पूर्ण",
    regCompleteDesc: "बच्चे का रिकॉर्ड जोड़ दिया गया है।",
    regFailed: "पंजीकरण विफल",
    regFailedDesc: "बच्चे का रिकॉर्ड सहेजने में असमर्थ।",
    ok: "ठीक है",
    enterName: "अपना नाम दर्ज करें",
    securityAccess: "सुरक्षा और पहुंच",
    secureOtpActive: "सुरक्षित एसएमएस ओटीपी लॉगिन सक्रिय",
    secureOtpDesc: "यह पोर्टल विवरणों को सुरक्षित रखने और पासवर्ड चोरी से बचने के लिए सुरक्षित वन-टाइम-पासकोड (OTP) सत्यापन का उपयोग करता है। कोड +91 पर भेजे जाते हैं।",
    biometricsDesc: "डिवाइस FaceID या TouchID का उपयोग करके प्रमाणित करें",
    activeSession: "वर्तमान सक्रिय सत्र",
    activeDeviceAccess: "सक्रिय डिवाइस पहुंच (मुख्य मोबाइल)",
    closeSecurity: "सुरक्षा पैनल बंद करें",
    notifPreferences: "अधिसूचना प्राथमिकताएं",
    criticalAlertsDesc: "चिकित्सीय स्थानांतरण या तत्काल रेफरल के लिए एसएमएस अलर्ट",
    followupRemindersDesc: "आंगनवाड़ी स्क्रीनिंग से 48 घंटे पहले एसएमएस अलर्ट",
    helplineUpdatesDesc: "स्वास्थ्य शिविरों और बाल चिकित्सा सेवाओं के बारे में घोषणाएं",
    saveNotifSettings: "अधिसूचना प्राथमिकताएं सहेजें",
    preferencesSaved: "प्राथमिकताएं सहेजी गईं",
    notifPreferencesUpdated: "आपकी अधिसूचना प्राथमिकताएं अपडेट कर दी गई हैं।",
    termsScopeTitle: "1. आवेदन का दायरा",
    termsScopeText: "यह पोर्टल छत्तीसगढ़ में बाल स्वास्थ्य स्क्रीनिंग (सैम/मैम मामलों) की सहायता के लिए विकसित किया गया है, जो राष्ट्रीय स्वास्थ्य मिशन और एकीकृत बाल विकास सेवाओं (ICDS) के दिशानिर्देशों के तहत काम करता है।",
    termsPrivacyTitle: "2. स्वास्थ्य डेटा गोपनीयता",
    termsPrivacyText: "बाल स्वास्थ्य संकेतक, वजन रिकॉर्ड और स्क्रीनिंग तिथियां ई-गवर्नेंस सुरक्षा मानकों के तहत सुरक्षित हैं। किसी भी व्यावसायिक सेवा के लिए कोई जानकारी साझा या वितरित नहीं की जाती है।",
    termsSecurityTitle: "3. सुरक्षा उपाय",
    termsSecurityText: "मोबाइल नंबर सत्यापन और सुरक्षित टोकन भंडारण यह सुनिश्चित करते हैं कि स्वास्थ्य रिकॉर्ड प्रामाणिक रहें और अनधिकृत छेड़छाड़ से सुरक्षित रहें।",
    acceptUnderstand: "मैं स्वीकार और समझता हूँ",
    logoutBtnText: "रजिस्ट्री से लॉगआउट करें",
    confirmLogout: "लॉगआउट की पुष्टि करें",
    logoutMessage: "क्या आप वाकई एनआरसी ई-गवर्नेंस पोर्टल से लॉगआउट करना चाहते हैं?",
    errorLabel: "त्रुटि",
    nameRequiredCaregiver: "अभिभावक का नाम आवश्यक है",
    failedUpdate: "प्रोफ़ाइल अपडेट करने में विफल",
    appVersionText: "ऐप संस्करण 1.0.0 (एनआईसी छत्तीसगढ़) · महिला एवं बाल विकास विभाग के तहत विकसित",
    verifiedAccount: "सत्यापित खाता",

    // Districts
    raipur: "रायपुर",
    durg: "दुर्ग",
    bastar: "बस्तर",
    bilaspur: "बिलासपुर",
    rajnandgaon: "राजनांदगांव",

    // Input Placeholders
    weightPlaceholder: "उदा. 8.5",
    heightPlaceholder: "उदा. 72",
    muacPlaceholder: "उदा. 112",

    // Landing Page
    landingTitle: "एनआरसी ई-गवर्नेंस",
    landingSubtitle: "छत्तीसगढ़ में पोषण पुनर्वास निगरानी के लिए एक एकीकृत मंच।",
    officialPortal: "आधिकारिक पोर्टल",
    registerTitle: "पंजीकरण",
    registerSub: "क्षेत्रीय कर्मचारियों और अभिभावकों के लिए सुरक्षित पंजीकरण।",
    registerMobileBtn: "मोबाइल से पंजीकरण करें",
    registerGmailBtn: "जीमेल से पंजीकरण करें",
    loginTitle: "लॉगिन",
    loginSub: "अपने डैशबोर्ड, रिपोर्ट और बच्चों के स्वास्थ्य रिकॉर्ड तक तुरंत पहुंचें।",
    loginPasswordBtn: "पासवर्ड से लॉगिन",
    loginOtpBtn: "ओटीपी से लॉगिन",
    nrcCentersStat: "एनआरसी केंद्र",
    childrenMonitoredStat: "निगरानी किए गए बच्चे",
    samRecoveryStat: "सैम से सुधार दर",
    trustedGov: "सरकारी एजेंसियों द्वारा विश्वसनीय",
    platformTrustText: "यह मंच एनआरसी पारिस्थितिकी तंत्र में पारदर्शिता, सशक्तिकरण और वास्तविक समय के निर्णयों के लिए बनाया गया है।",
    poweredByNic: "एनआईसी · महिला एवं बाल विकास मंत्रालय द्वारा संचालित",

    // Login Screen
    govCg: "छत्तीसगढ़ सरकार",
    nrcGovPortal: "एनआरसी ई-गवर्नेंस पोर्टल",
    welcome: "स्वागत है!",
    loginPhoneSub: "अपने मोबाइल नंबर से लॉगिन करें",
    enterOtpSub: "आपके मोबाइल पर भेजा गया ओटीपी दर्ज करें",
    mobileNumber: "मोबाइल नंबर",
    enterMobilePlaceholder: "अपना 10-अंकीय मोबाइल नंबर दर्ज करें",
    requestOtp: "ओटीपी का अनुरोध करें",
    enterOtp: "ओटीपी दर्ज करें",
    enterOtpPlaceholder: "6-अंकीय ओटीपी दर्ज करें",
    verifyOtp: "ओटीपी सत्यापित करें",
    backPhoneEntry: "मोबाइल नंबर पर वापस जाएं",
    secureGovPortalText: "यह एक सुरक्षित सरकारी पोर्टल है। अनधिकृत पहुंच प्रतिबंधित है।",
    dontHaveAccount: "खाता नहीं है?",
    createAccount: "खाता बनाएं",
    phoneRequired: "कृपया एक मान्य मोबाइल नंबर दर्ज करें",
    otpRequired: "कृपया एक मान्य ओटीपी दर्ज करें",
    otpSentSuccess: "ओटीपी सफलतापूर्वक भेजा गया",
    failedSendOtp: "ओटीपी भेजने में विफल",
    invalidOtp: "अमान्य ओटीपी",

    // Register Screen
    startRegistration: "अपना पंजीकरण शुरू करें",
    welcomeNrcGov: "एनआरसी ई-गवर्नेंस में आपका स्वागत है",
    registerCardCopy: "एक सुरक्षित खाता बनाने और सरकारी सेवाओं तक पहुंचने का अपना पसंदीदा तरीका चुनें।",
    professionalRole: "पेशेवर भूमिका",
    selectRole: "भूमिका चुनें",
    govEmailLabel: "सरकारी ईमेल (गैर-अभिभावक भूमिकाओं के लिए आवश्यक)",
    govEmailPlaceholder: "name@domain.gov.in",
    selectRoleError: "कृपया एक पेशेवर भूमिका चुनें",
    govEmailRequired: "अभिभावक के अलावा अन्य भूमिकाओं के लिए सरकारी ईमेल आवश्यक है",
    gmailRegisterAlertTitle: "गूगल प्रमाणीकरण",
    gmailRegisterAlertMsg: "गूगल पंजीकरण एकीकरण एक्सपो ऑथ-सत्र (AuthSession) का उपयोग करेगा।",

    // OTP Verification
    verifyMobileNum: "मोबाइल नंबर सत्यापित करें",
    mobileNumLogin: "मोबाइल नंबर लॉगिन",
    enterOtpReg: "पंजीकरण जारी रखने के लिए ओटीपी दर्ज करें",
    receiveCodeMobile: "अपने मोबाइल पर एक बार का कोड प्राप्त करें",
    sendOtpBtn: "ओटीपी भेजें",
    verificationCode: "सत्यापन कोड",
    verifyContinueBtn: "सत्यापित करें और जारी रखें",
    verifyLoginBtn: "सत्यापित करें और लॉगिन करें",
    useDiffNum: "दूसरे नंबर का उपयोग करें",
    secureVerification: "सुरक्षित सत्यापन",
    otpValidityNote: "ओटीपी केवल कुछ समय के लिए मान्य है और इसका उपयोग आपके खाते को एक विश्वसनीय सरकारी लॉगिन अनुभव के साथ सुरक्षित रखने के लिए किया जाता है।",
    otpSentTitle: "ओटीपी भेजा गया",
    otpSentMsg: "आपका सत्यापन कोड भेज दिया गया है।",
    enterOtpCodeError: "6-अंकीय ओटीपी दर्ज करें",
    otpVerificationFailed: "ओटीपी सत्यापन विफल रहा",

    // Full Registration
    fullRegistrationTitle: "पूर्ण पंजीकरण",
    completeDetailsText: "पंजीकरण पूरा करने के लिए अपने खाते का विवरण भरें।",
    fullNameLabel: "पूरा नाम",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    emailAddressLabel: "ईमेल पता",
    enterEmailAddress: "name@example.com",
    createPasswordPlaceholder: "पासवर्ड बनाएं",
    confirmPasswordPlaceholder: "पासवर्ड की पुष्टि करें",
    fieldsRequiredError: "सभी क्षेत्र आवश्यक हैं।",
    passwordsMismatchError: "पासवर्ड मेल नहीं खाते।",
    regSuccessTitle: "पंजीकरण पूर्ण",
    regSuccessMsg: "आपका खाता सफलतापूर्वक बना दिया गया है।",
    continueBtn: "जारी रखें",
    infoProtectedTitle: "आपकी जानकारी सुरक्षित है",
    infoProtectedBody: "सभी पंजीकरण विवरण सुरक्षित रूप से संग्रहीत किए जाते हैं और केवल अधिकृत एनआरसी ई-गवर्नेंस पहुंच के लिए उपयोग किए जाते हैं।",

    // Component label keys
    passwordLabel: "पासवर्ड",
    confirmPasswordLabel: "पासवर्ड की पुष्टि करें",
    govPortalManagedText: "यह पोर्टल छत्तीसगढ़ सरकार द्वारा प्रबंधित है और विश्वसनीय सार्वजनिक सेवा पहुंच के लिए बनाया गया है।",
    mothersName: "माता का नाम",
    mothersPhone: "माता का मोबाइल नंबर",
    anganwadiVillage: "आंगनवाड़ी गाँव",
    lastAssessmentDate: "अंतिम जांच की तारीख",
    referToNrc: "पोषण पुनर्वास केंद्र रेफर करें",
    admittedToNrcTitle: "पोषण पुनर्वास केंद्र में भर्ती",
    familyContextTitle: "पारिवारिक विवरण और जानकारी",
    samDiagnosticsIdentified: "सैम कुपोषण की पहचान",
    growthProgressRegistered: "विकास प्रगति दर्ज की गई",
    mamDiagnosticCheck: "मैम कुपोषण जांच",
    standardHealthRecalibrated: "सामान्य स्वास्थ्य बहाल",
    totalRegisteredProfiles: "कुल पंजीकृत प्रोफाइल",
    syncingRegistry: "राज्य रजिस्ट्री सिंक्रनाइज़ हो रही है...",
    syncFailed: "सिंक्रनाइज़ेशन विफल रहा",
    matchingRecords: "मिलान वाले रिकॉर्ड",
    registryEmpty: "रजिस्ट्री खाली है",
    noChildrenSync: "कोई भी बच्चे की प्रोफाइल सिंक्रनाइज़ नहीं हुई है। पुनः प्रयास करने के लिए नीचे क्लिक करें।",
    allNotificationsMarkedRead: "सभी सूचनाएं पढ़ी गई चिह्नित की गईं",
    clearNotifications: "सूचनाएं हटाएं",
    confirmDeleteAllNotifications: "क्या आप वाकई सभी सूचना रिकॉर्ड हटाना चाहते हैं?",
    clearAll: "सभी हटाएं",
    unreadNotifications: "बिना पढ़े संदेसा मन",
    followupsTab: "फॉलो-अप",
    alertsTab: "अलर्ट",
    nrcReferralsTab: "भर्ती",
    markAllRead: "सभी पढ़ें",
    clearAllAction: "सभी हटाएं",
    registeredStep: "पंजीकृत",
    screenedStep: "जांच पूर्ण",
    referredStep: "रेफर किया",
    nrcAdmittedStep: "एनआरसी भर्ती",
    noChildrenRegistered: "कोई बच्चा पंजीकृत नहीं है",
    selectChildProfile: "बच्चे की प्रोफाइल चुनें",
    viewDevelopmentHistory: "विकास इतिहास और चार्ट देखें",
    remindersNutritionalTips: "अनुस्मारक और पोषण संबंधी युक्तियाँ",
    nextAssessmentDue: "अगला मूल्यांकन नियत तारीख",
    scheduledFor: "लगभग अनुसूचित है:",
    checksRequiredBimonthly: "द्वि-मासिक जांच आवश्यक है।",
    nutritionalGuideline: "पोषण संबंधी दिशा-निर्देश",
    dashboardFooterText: "महिला एवं बाल विकास विभाग · छत्तीसगढ़ सरकार",
    activeBedCapacityAvailable: "{district} जिला में सक्रिय बेड क्षमता उपलब्ध है। भर्ती करने के लिए यहाँ टैप करें।",
    recSamFormula: "चिकित्सीय देखरेख में तुरंत एफ-75 (F-75) चिकित्सीय फार्मूला शुरू करें।",
    recMamFormula: "दैनिक रूप से रेडी-टू-यूज चिकित्सीय भोजन (RUTF) के 2 पैकेट प्रदान करें।",
    recHealthyFormula: "ऊंचाई और वजन सामान्य है। नियमित टीकाकरण, सूक्ष्म पोषक तत्व और जांच जारी रखें।",
    recMuacWarning: "हर 7 दिनों में बांह का घेरा (MUAC) मापें। यदि यह 110 मिमी से कम हो, तो तत्काल डॉक्टर से संपर्क करें।",
    assignedDistrictHospitalNrc: "आवंटित जिला अस्पताल एनआरसी केंद्र",
    activeReferralPlacement: "सक्रिय रेफरल और भर्ती",
    callCenterCoordinator: "कॉल सेंटर समन्वयक से बात करें",
    primaryCareFacility: "प्राथमिक स्वास्थ्य सेवा",
    anganwadiCenterAwc: "आंगनवाड़ी केंद्र (AWC)",
    localVillageCenter: "स्थानीय गाँव केंद्र",
    icdsProgram: "कार्यक्रम: एकीकृत बाल विकास सेवा (ICDS)",
    messageMitaninField: "मितानिन / फील्ड वर्कर को संदेश भेजें",
    registerChildDesc: "बाल चिकित्सा बढ़त, फॉलो-अप शेड्यूल देखने और पोषण संबंधी अनुशंसाएं प्राप्त करने के लिए अपने मोबाइल नंबर का उपयोग करके बच्चे को पंजीकृत करें।",
    adviceSamGuide: "चिकित्सीय आरयूटीएफ (RUTF) और एफ-75 (F-75) दूध फार्मूला प्रदान करें; अगले क्लीनिकल मूल्यांकन तक ठोस अनाज से बचें।",
    adviceNormalGuide: "आंगनवाड़ी केंद्र से दैनिक पूरक पोषण सुनिश्चित करें, विशेषकर प्रोटीन और आयरन युक्त आहार दें।",
  },
  cg: {
    // Tabs & General
    dashboard: "डैशबोर्ड",
    children: "लरिका मन",
    notifications: "सूचना मन",
    profile: "प्रोफाइल",
    reports: "रिपोर्ट",
    funds: "फंड",
    
    // Dashboard
    parentPortal: "अभिभावक पोर्टल",
    welcomeBack: "जय जोहार, अभिभावक दीदी!",
    vitalsSummary: "स्वास्थ्य संकेतक",
    weight: "वजन",
    height: "ऊंचाई",
    muac: "एमयूएसी (MUAC)",
    growthTrend: "बढ़त की स्थिति",
    recoveryTimeline: "रिकवरी समयरेखा",
    screeningJourney: "जांच यात्रा",
    assignedFacility: "स्वास्थ्य केंद्र",
    mitaninSupport: "मितानिन दीदी के मदद",
    recentAlerts: "नवा संदेश मन",
    registerChildBtn: "लरिका के पंजीयन करव",
    callBtn: "फोन करव",
    messageMitanin: "मितानिन दीदी ला संदेसा भेजव...",
    weightGain: "वजन बढ़िस",
    weightLoss: "वजन कम होइस",
    noChange: "कोनो बदलाव नई",
    screeningTip: "जांच के सुरता दिलाए बर",
    screeningIntervalSam: "सैम/मैम (SAM/MAM) से पीड़ित लरिका मन के बने जांच बर हर 15 दिन म जांच कराय बर चाही।",
    screeningIntervalNormal: "बने लरिका मन के सही बढ़त बर हर 30 दिन म जांच कराय बर चाही।",
    recoveryMilestones: "रिकवरी यात्रा के पड़ाव",
    facilityHelp: "अस्पताल के जानकारी",
    noAlerts: "कोनो नवा संदेसा नई मिले हे।",

    // Children Screen
    childrenList: "लरिका मन के सूची",
    searchPlaceholder: "लरिका या गाँव खोजव...",
    all: "जम्मो",
    sam: "सैम (SAM)",
    mam: "मैम (MAM)",
    healthy: "बने हे (स्वस्थ)",
    viewProfile: "प्रोफाइल देखव",
    noChildren: "कोनो लरिका नई मिलिस।",
    districtLabel: "जिला",
    villageLabel: "गाँव",
    dobLabel: "जनम तारीख",
    retryBtn: "फेर कोसिस करव",
    errorLoading: "पंजीकृत लरिका मन के प्रोफाइल नई मिल पाइस।",

    // Child Details
    childDetails: "लरिका के विवरण",
    clinicalAdvice: "डाक्टर के सलाह",
    growthChart: "बढ़त चार्ट",
    weightHistory: "वजन के बढ़त (किग्रा)",
    assessmentLog: "जांच विवरण",
    date: "तारीख",
    dob: "जनम तारीख",
    gender: "लिंग",
    nrcCenter: "एनआरसी (NRC) केंद्र",
    notAssigned: "आवंटित नई हे",
    noLogs: "कोनो सेहत रेकार्ड नई मिले हे।",
    admissionBtn: "एनआरसी म भरती करव",
    admittedNrc: "एनआरसी म भरती हे",

    // Profile
    myProfile: "मोर प्रोफाइल",
    accountSettings: "खाता सेटिंग्स",
    editProfile: "विवरण बदलव",
    regDistrict: "जिला",
    securityPassword: "सुरक्षा और पासवर्ड",
    preferencesHelp: "पसंद अउ मदद",
    notifSettings: "सूचना सेटिंग्स",
    langSelector: "भाषा बदलव",
    supportHelpline: "मदद अउ हेल्पलाइन",
    termsPrivacy: "नियम अउ गोपनीयता नीति",
    logout: "लॉगआउट",
    saveChanges: "सहेजव",
    cancel: "रद्द करव",
    nameLabel: "अभिभावक के नाम",
    phoneLabel: "मोबाइल नंबर",
    selectDistrict: "जिला चुनव",
    biometrics: "फिंगरप्रिंट लॉगिन चालू करव",
    criticalAlertsOpt: "कुपोषण संदेश प्राप्त करव",
    followupRemindersOpt: "जांच बर सुरता संदेसा",
    helplineUpdatesOpt: "हेल्पलाइन आपातकालीन नवा संदेसा",
    applyLanguageBtn: "चुन ले भाषा बदलव",
    supportIntro: "सहायता बर सीधे फोन मिलाव:",
    stateWcd: "महिला एवं बाल विकास हेल्पलाइन",
    stateWcdDesc: "आंगनबाड़ी अउ पोषण किट के जानकारी बर",
    emergencyHealth: "आपातकालीन स्वास्थ्य सेवा",
    emergencyHealthDesc: "लरिका मन के सेहत अउ इलाज बर सलाह बर",
    mitaninSupportLine: "मितानिन मदद हेल्पलाइन",
    mitaninSupportLineDesc: "मितानिन दीदी के जांच के जानकारी बर",
    childInfo: "लरिका के जानकारी",
    childName: "लरिका के पूरा नाम",
    measurements: "शरीर के माप",
    parentMobile: "मोबाइल नंबर",
    healthStatus: "स्वास्थ्य के स्थिति",
    locationDetails: "पता के विवरण",
    village: "गाँव / वार्ड",
    anganwadiCode: "आंगनवाड़ी केंद्र कोड",
    registerBtn: "पंजीयन करव",
    childRegistrationTitle: "लरिका के पंजीयन",
    samIntakeForm: "सैम (SAM) भर्ती फॉर्म",
    childFullName: "लरिका के पूरा नाम",
    enterChildName: "लरिका के पूरा नाम लिखव",
    dobPlaceholder: "दिन/महीना/साल",
    male: "पुरुष",
    female: "महिला",
    others: "दूसर",
    selectGenderError: "लिंग चुनव",
    motherName: "दाई के नाम",
    enterMotherName: "दाई या अभिभावक के नाम लिखव",
    parentMobilePlaceholder: "10-अंकीय मोबाइल नंबर",
    weightKg: "वजन (किग्रा)",
    heightCm: "ऊंचाई (सेमी)",
    muacMm: "एमयूएसी (मिमी)",
    villageWard: "गाँव / वार्ड क्षेत्र",
    enterVillage: "गाँव या वार्ड क्षेत्र लिखव",
    enterAnganwadiCode: "आंगनवाड़ी कोड लिखव",
    submitRegistration: "पंजीयन जमा करव",
    cancelRegistration: "पंजीयन रद्द करव",
    saving: "सहेजत हे...",
    nameRequired: "लरिका के पूरा नाम जरूरी हे",
    dobRequired: "जनम तारीख जरूरी हे",
    dobFormat: "DD/MM/YYYY फार्मेट म लिखव",
    motherNameRequired: "दाई के नाम जरूरी हे",
    mobileFormat: "मोबाइल नंबर 10 अंकों के होना चाही",
    weightRequired: "वजन जरूरी हे",
    heightRequired: "ऊंचाई जरूरी हे",
    muacRequired: "एमयूएसी जरूरी हे",
    districtRequired: "जिला जरूरी हे",
    anganwadiRequired: "आंगनवाड़ी कोड जरूरी हे",
    villageRequired: "गाँव / क्षेत्र जरूरी हे",
    regComplete: "पंजीयन पूरा होइस",
    regCompleteDesc: "लरिका के जानकारी जोड़ दिए गए हे।",
    regFailed: "पंजीयन नई हो पाइस",
    regFailedDesc: "लरिका के जानकारी सहेजे म असमर्थ।",
    ok: "बने हे",
    enterName: "अपन नाम लिखव",
    securityAccess: "सुरक्षा अउ पहुंच",
    secureOtpActive: "सुरक्षित एसएमएस ओटीपी लॉगिन चालू हे",
    secureOtpDesc: "यह पोर्टल जानकारी ला सुरक्षित रखे बर सुरक्षित वन-टाइम-पासकोड (OTP) के उपयोग करथे। कोड +91 म भेजे जाथे।",
    biometricsDesc: "डिवाइस फिंगरप्रिंट या FaceID के उपयोग करव",
    activeSession: "अभी चालू सत्र",
    activeDeviceAccess: "चालू डिवाइस पहुंच (मुख्य मोबाइल)",
    closeSecurity: "सुरक्षा पैनल बंद करव",
    notifPreferences: "सूचना प्राथमिकता मन",
    criticalAlertsDesc: "इलाज बर अस्पताल भेजे या तुरंत रेफरल बर एसएमएस संदेश",
    followupRemindersDesc: "आंगनबाड़ी जांच से 48 घंटा पहली एसएमएस संदेश",
    helplineUpdatesDesc: "स्वास्थ्य शिविर अउ लरिका मन के इलाज बर जानकारी",
    saveNotifSettings: "सूचना प्राथमिकता मन ला सहेजव",
    preferencesSaved: "प्राथमिकता मन सहेज लिए गए हे",
    notifPreferencesUpdated: "आपकी सूचना प्राथमिकता मन बदल दिए गए हे।",
    termsScopeTitle: "1. काम के दायरा",
    termsScopeText: "यह पोर्टल छत्तीसगढ़ म लरिका मन के जांच (सैम/मैम बीमारी) म मदद बर बनाए गए हे, जउन राष्ट्रीय स्वास्थ्य मिशन अउ एकीकृत बाल विकास सेवा (ICDS) के नियम म काम करथे।",
    termsPrivacyTitle: "2. स्वास्थ्य जानकारी के गोपनीयता",
    termsPrivacyText: "लरिका मन के माप, वजन अउ जांच के तारीख मन ई-गवर्नेंस सुरक्षा म सुरक्षित हे। कोनो भी जानकारी बेचे या कोनो ला दिए नई जाय।",
    termsSecurityTitle: "3. सुरक्षा के उपाय",
    termsSecurityText: "मोबाइल नंबर जांच अउ सुरक्षित टोकन यह पक्का करथे कि सेहत के जानकारी सही अउ सुरक्षित रहे।",
    acceptUnderstand: "मैं स्वीकार अउ समझथंव",
    logoutBtnText: "रजिस्ट्री से लॉगआउट करव",
    confirmLogout: "लॉगआउट पक्का करव",
    logoutMessage: "क्या आप सच म एनआरसी ई-गवर्नेंस पोर्टल से लॉगआउट करना चाहथो?",
    errorLabel: "गड़बड़",
    nameRequiredCaregiver: "अभिभावक के नाम जरूरी हे",
    failedUpdate: "प्रोफ़ाइल बदले म असमर्थ",
    appVersionText: "ऐप संस्करण 1.0.0 (एनआईसी छत्तीसगढ़) · महिला एवं बाल विकास विभाग के तहत विकसित",
    verifiedAccount: "सत्यापित खाता",

    // Districts
    raipur: "रायपुर",
    durg: "दुरग",
    bastar: "बस्तर",
    bilaspur: "बिलासपुर",
    rajnandgaon: "राजनांदगांव",

    // Input Placeholders
    weightPlaceholder: "उदा. 8.5",
    heightPlaceholder: "उदा. 72",
    muacPlaceholder: "उदा. 112",

    // Landing Page
    landingTitle: "एनआरसी ई-गवर्नेंस",
    landingSubtitle: "छत्तीसगढ़ म लरिका मन के पोषण पुनर्वास निगरानी बर एक मंच।",
    officialPortal: "सरकारी पोर्टल",
    registerTitle: "पंजीयन",
    registerSub: "फील्ड स्टाफ अउ अभिभावक मन बर सुरक्षित पंजीयन।",
    registerMobileBtn: "मोबाइल से पंजीयन करव",
    registerGmailBtn: "जीमेल से पंजीयन करव",
    loginTitle: "लॉगिन",
    loginSub: "अपन डैशबोर्ड, रिपोर्ट अउ लरिका मन के सेहत रिकॉर्ड ला तुरंत देखव।",
    loginPasswordBtn: "पासवर्ड से लॉगिन",
    loginOtpBtn: "ओटीपी से लॉगिन",
    nrcCentersStat: "एनआरसी केंद्र",
    childrenMonitoredStat: "जांच करे गए लरिका",
    samRecoveryStat: "सैम से सुधार दर",
    trustedGov: "सरकारी विभाग मन के भरोसा",
    platformTrustText: "यह मंच एनआरसी व्यवस्था म पारदर्शिता अउ तुरंत निर्णय बर बनाए गए हे।",
    poweredByNic: "एनआईसी · महिला अउ लरिका विकास विभाग द्वारा संचालित",

    // Login Screen
    govCg: "छत्तीसगढ़ सरकार",
    nrcGovPortal: "एनआरसी ई-गवर्नेंस पोर्टल",
    welcome: "जय जोहार!",
    loginPhoneSub: "अपन मोबाइल नंबर से लॉगिन करव",
    enterOtpSub: "मोबाइल म भेजे गए ओटीपी ला लिखव",
    mobileNumber: "मोबाइल नंबर",
    enterMobilePlaceholder: "अपन 10-अंकीय मोबाइल नंबर लिखव",
    requestOtp: "ओटीपी के अनुरोध करव",
    enterOtp: "ओटीपी लिखव",
    enterOtpPlaceholder: "6-अंकीय ओटीपी लिखव",
    verifyOtp: "ओटीपी जांचव",
    backPhoneEntry: "मोबाइल नंबर म वापस जाव",
    secureGovPortalText: "यह सुरक्षित सरकारी पोर्टल हे। बिना अनुमति पहुंच मना हे।",
    dontHaveAccount: "खाता नई हे?",
    createAccount: "खाता बनाव",
    phoneRequired: "कृपया सही मोबाइल नंबर लिखव",
    otpRequired: "कृपया सही ओटीपी लिखव",
    otpSentSuccess: "ओटीपी भेज दिए गए हे",
    failedSendOtp: "ओटीपी भेजे म गड़बड़ होइस",
    invalidOtp: "गलत ओटीपी",

    // Register Screen
    startRegistration: "अपन पंजीयन शुरू करव",
    welcomeNrcGov: "एनआरसी ई-गवर्नेंस म स्वागत हे",
    registerCardCopy: "सुरक्षित खाता बनाए अउ सरकारी सुविधा मन ला पाए बर अपन तरीका चुनव।",
    professionalRole: "काम के भूमिका",
    selectRole: "भूमिका चुनव",
    govEmailLabel: "सरकारी ईमेल (दूसर भूमिका मन बर जरूरी हे)",
    govEmailPlaceholder: "name@domain.gov.in",
    selectRoleError: "कृपया काम के भूमिका चुनव",
    govEmailRequired: "अभिभावक के अलावा दूसर काम बर सरकारी ईमेल जरूरी हे",
    gmailRegisterAlertTitle: "गूगल सत्यापन",
    gmailRegisterAlertMsg: "गूगल पंजीयन बर एक्सपो ऑथ-सत्र (AuthSession) के उपयोग होही।",

    // OTP Verification
    verifyMobileNum: "मोबाइल नंबर जांचव",
    mobileNumLogin: "मोबाइल नंबर लॉगिन",
    enterOtpReg: "पंजीयन आगे बढ़ाए बर ओटीपी लिखव",
    receiveCodeMobile: "मोबाइल म एक बार के कोड (OTP) पाव",
    sendOtpBtn: "ओटीपी भेजव",
    verificationCode: "सत्यापन कोड",
    verifyContinueBtn: "जांचव अउ आगे बढ़व",
    verifyLoginBtn: "जांचव अउ लॉगिन करव",
    useDiffNum: "दूसर नंबर के उपयोग करव",
    secureVerification: "सुरक्षित जांच",
    otpValidityNote: "ओटीपी थोरकिन समय बर काम करथे अउ यह अपन खाता ला सुरक्षित रखे बर हे।",
    otpSentTitle: "ओटीपी भेजिस",
    otpSentMsg: "सत्यापन कोड भेज दिए गए हे।",
    enterOtpCodeError: "6-अंकीय ओटीपी लिखव",
    otpVerificationFailed: "ओटीपी जांच म गड़बड़ होइस",

    // Full Registration
    fullRegistrationTitle: "पूरा पंजीयन",
    completeDetailsText: "पंजीयन पूरा करे बर अपन खाता के जानकारी लिखव।",
    fullNameLabel: "पूरा नाम",
    enterFullName: "अपन पूरा नाम लिखव",
    emailAddressLabel: "ईमेल पता",
    enterEmailAddress: "name@example.com",
    createPasswordPlaceholder: "पासवर्ड बनाव",
    confirmPasswordPlaceholder: "पासवर्ड पक्का करव",
    fieldsRequiredError: "जम्मो जानकारी लिखना जरूरी हे।",
    passwordsMismatchError: "पासवर्ड नई मिलिस।",
    regSuccessTitle: "पंजीयन पूरा होइस",
    regSuccessMsg: "अपन खाता सफलतापूर्वक बना लिए गए हे।",
    continueBtn: "आगे बढ़व",
    infoProtectedTitle: "अपन जानकारी सुरक्षित हे",
    infoProtectedBody: "जम्मो पंजीयन जानकारी ला सुरक्षित रखे जाथे अउ केवल एनआरसी काम म उपयोग होही।",

    // Component label keys
    passwordLabel: "पासवर्ड",
    confirmPasswordLabel: "पासवर्ड पक्का करव",
    govPortalManagedText: "यह पोर्टल छत्तीसगढ़ सरकार द्वारा प्रबंधित हे अउ सरकारी काम बर बनाए गए हे।",
    mothersName: "दाई के नाम",
    mothersPhone: "दाई के मोबाइल नंबर",
    anganwadiVillage: "आंगनवाड़ी गाँव",
    lastAssessmentDate: "जांच के तारीख",
    referToNrc: "अस्पताल म रेफर करव",
    admittedToNrcTitle: "एनआरसी म भर्ती",
    familyContextTitle: "पारिवारिक विवरण अउ जानकारी",
    samDiagnosticsIdentified: "सैम बीमारी के पहचान",
    growthProgressRegistered: "बढ़त दर्ज करे गए हे",
    mamDiagnosticCheck: "मैम बीमारी जांच",
    standardHealthRecalibrated: "स्वास्थ्य बने होइस",
    totalRegisteredProfiles: "कुल पंजीकृत प्रोफाइल",
    syncingRegistry: "जानकारी ला सिंक्रनाइज़ करत हे...",
    syncFailed: "सिंक्रनाइज़ेशन म गड़बड़ होइस",
    matchingRecords: "मिलान वाले रिकॉर्ड",
    registryEmpty: "रजिस्ट्री खाली हे",
    noChildrenSync: "कोनो लरिका के जानकारी नई सिंक्रनाइज़ होइस। कोशिश बर नीचे क्लिक करव।",
    allNotificationsMarkedRead: "जम्मू संदेसा मन ला पढ़ ले गए हे",
    clearNotifications: "संदेसा मन ला हटाव",
    confirmDeleteAllNotifications: "क्या आप सच म जम्मो संदेसा मन ला हटाना चाहथो?",
    clearAll: "जम्मो हटाव",
    unreadNotifications: "बिना पढ़े संदेसा मन",
    followupsTab: "फॉलो-अप",
    alertsTab: "अलर्ट",
    nrcReferralsTab: "भर्ती",
    markAllRead: "जम्मू ला पढ़ ले लिखव",
    clearAllAction: "जम्मो मिटाव",
    registeredStep: "पंजीकृत",
    screenedStep: "जांच पूर्ण",
    referredStep: "रेफर करिस",
    nrcAdmittedStep: "एनआरसी भर्ती",
    noChildrenRegistered: "कोनो लरिका पंजीकृत नई हे",
    selectChildProfile: "लरिका के प्रोफाइल चुनव",
    viewDevelopmentHistory: "लरिका के बढ़त अउ चार्ट देखव",
    remindersNutritionalTips: "सुझाव अउ पोषण जानकारी",
    nextAssessmentDue: "अगला जांच के तारीख",
    scheduledFor: "लगभग अनुसूचित हे:",
    checksRequiredBimonthly: "हर महीना म जांच जरूरी हे।",
    nutritionalGuideline: "पोषण संबंधी जानकारी",
    dashboardFooterText: "महिला अउ लरिका विकास विभाग · छत्तीसगढ़ सरकार",
    activeBedCapacityAvailable: "{district} जिला म बेड खाली हे। भर्ती करे बर यहाँ क्लिक करव।",
    recSamFormula: "डॉक्टर के देखरेख म तुरंत एफ-75 चिकित्सीय फार्मूला शुरू करव।",
    recMamFormula: "हर दिन लरिका बर रेडी-टू-यूज चिकित्सीय भोजन (RUTF) के 2 पैकेट देव।",
    recHealthyFormula: "लरिका के बढ़त सही हे। नियमित टीका, पोषण पाउडर अउ जांच जारी रखव।",
    recMuacWarning: "हर 7 दिन म बांह के घेरा (MUAC) नापव। यदि 110 मिमी से कम हो, तो तुरंत अस्पताल ले जाव।",
    assignedDistrictHospitalNrc: "आवंटित जिला अस्पताल एनआरसी केंद्र",
    activeReferralPlacement: "सक्रिय रेफरल अउ भरती",
    callCenterCoordinator: "कॉल सेंटर म बात करव",
    primaryCareFacility: "प्राथमिक स्वास्थ्य सेवा",
    anganwadiCenterAwc: "आंगनवाड़ी केंद्र (AWC)",
    localVillageCenter: "गाँव के केंद्र",
    icdsProgram: "कार्यक्रम: एकीकृत बाल विकास सेवा (ICDS)",
    messageMitaninField: "मितानिन / फील्ड वर्कर ला संदेसा भेजव",
    registerChildDesc: "लरिका के बढ़त, जांच के तारीख मन ला देखव अउ पोषण जानकारी पाए बर अपन मोबाइल नंबर ले पंजीयन करव।",
    adviceSamGuide: "चिकित्सीय आरयूटीएफ (RUTF) अउ एफ-75 (F-75) दूध देव; अगम जांच तक ठोस अनाज नई देव।",
    adviceNormalGuide: "आंगनवाड़ी केंद्र से हर दिन के पोषण खुराक सुनिश्चित करव, प्रोटीन अउ लोहा (आयरन) वाला खाना देव।",
  }
};

export const LanguageContext = createContext<LanguageContextProps>({
  locale: 'en',
  setLocale: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<LocaleType>('en');

  useEffect(() => {
    // Load persisted language from Storage
    const loadLocale = async () => {
      try {
        const storedLocale = await AsyncStorage.getItem('appLocale');
        if (storedLocale === 'en' || storedLocale === 'hi' || storedLocale === 'cg') {
          setLocaleState(storedLocale as LocaleType);
        }
      } catch (e) {
        console.warn('Failed to load locale:', e);
      }
    };
    loadLocale();
  }, []);

  const setLocale = async (newLocale: LocaleType) => {
    setLocaleState(newLocale);
    try {
      await AsyncStorage.setItem('appLocale', newLocale);
    } catch (e) {
      console.warn('Failed to save locale:', e);
    }
  };

  const t = (key: string): string => {
    return translations[locale][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
